### ISSUE TITLE
docker-compose requires update

### ISSUE THREAD

**Issue by mrtrkmn** [gianmarcomennecozzi/grpc-vue-go#10]
In docker compose, it is building image from scratch, it could be better if we define latest version of docker image which is hosted in github registry, proposed docker-compose file 

```
version: '3.4'
services:
  proxy:
    image: docker.pkg.github.com/aau-network-security/haaukins-webclient/envoy:v0.0.0
    ports:
      - '8000:8000'
    volumes:
      - ${CERTIFICATES_PATH}:/etc/certs
    networks:
      - haaukins-webclient
    env_file:
      - .env

  webclient:
    image: docker.pkg.github.com/aau-network-security/haaukins-webclient/webclient:v0.0.0
    ports:
      - '8003:8003'
    volumes:
      - ${CERTIFICATES_PATH}:/etc/certs
    networks:
      - haaukins-webclient
    env_file:
      - .env
networks:
  haaukins-webclient:

```
In this way, we do not have to rebuild the images,  however we still have to specify version of docker image  correctly !!.
